Fix runtime panic introduced by #436
kartverket/skiperator-poc pull request #437
Opened 2024-04-02 14:33 UTC by omaen

I introduced a runtime panic in #436 because I assumed that the default from the CRD was propogated to the reconciler. Added a test to catch the case.

2024-04-03 12:04 UTC, berg-thom approved these changes

2024-04-08 06:21 UTC, evenh requested changes

2024-04-08 06:21 UTC, evenh commented on controllers/application/service_monitor.go
This needs to be applied to pod_monitor.go as well + tests.

2024-04-08 10:05 UTC, evenh commented on controllers/application/service_monitor.go
`controllers/skipjob/pod_monitor.go`. It is susceptible to the same nil bug.

2024-04-08 11:06 UTC, evenh approved these changes

2024-04-08 11:31 UTC, merged